export const GET_DECKS='GET_DECKS';
export const GET_DECK='GET_DECK';
export const SAVE_DECK_TITLE='SAVE_DECK_TITLE';
export const ADD_CARD_TO_DECK='ADD_CARD_TO_DECK';
export const REMOVE_DECKS='REMOVE_DECKS';
export const SAVE_CARD_TO_DECK='SAVE_CARD_TO_DECK';